"topic:admin": topics/admin/**/*
"topic:assembly": topics/assembly/**/*
"topic:climate": topics/climate/**/*
"topic:computational-chemistry": topics/computational-chemistry/**/*
"topic:contributing": topics/contributing/**/*
"topic:data-science": topics/data-science/**/*
"topic:dev": topics/dev/**/*
"topic:ecology": topics/ecology/**/*
"topic:epigenetics": topics/epigenetics/**/*
"topic:galaxy-interface": topics/galaxy-interface/**/*
"topic:genome-annotation": topics/genome-annotation/**/*
"topic:imaging": topics/imaging/**/*
"topic:instructors": topics/instructors/**/*
"topic:introduction": topics/introduction/**/*
"topic:metabolomics": topics/metabolomics/**/*
"topic:metagenomics": topics/metagenomics/**/*
"topic:proteomics": topics/proteomics/**/*
"topic:sequence-analysis": topics/sequence-analysis/**/*
"topic:statistics": topics/statistics/**/*
"topic:transcriptomics": topics/transcriptomics/**/*
"topic:variant-analysis": topics/variant-analysis/**/*
"topic:visualisation": topics/visualisation/**/*

template-and-tools:
  - bin/**/*
  - _includes/**/*
  - _layouts/**/*
  - _plugins/**/*
  - assets/**/*
