name: Build GIT-GAT

on: [pull_request]
  #push:
    #branches:
      #- main

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - uses: actions/setup-python@v2
        with:
          python-version: '3.7'
          architecture: 'x64'

      - name: Build git-gat repo
        run: |
            bin/knit-automated.sh export;

      - name: Build git-gat repo
        run: |
            cd /tmp/git-gat/
            git config --global init.defaultBranch main
            git config --global user.email "galaxytrainingnetwork@gmail.com"
            git config --global user.name "The Galaxy Training Network"
            git init
            git am *.patch
            rm -f *.patch
            ls -al
            git remote add origin git@github.com:hexylena/git-gat
            git push -u origin main
