name: Build GIT-GAT

on:
  pull_request:
    paths:
      - 'topics/admin/**'
      - 'bin/knit*'
      - 'bin/video*'
  push:
    branches:
      - main
    paths:
      - 'topics/admin/**'
      - 'bin/knit*'
      - 'bin/video*'

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - uses: actions/setup-python@v2
        with:
          python-version: '3.7'
          architecture: 'x64'

      - name: Build git-gat repo
        run: |
            bin/knit-automated.sh export;

      - name: Build git-gat repo
        run: |
            cd /tmp/git-gat/
            git config --global init.defaultBranch main
            git config --global user.email "galaxytrainingnetwork@gmail.com"
            git config --global user.name "The Galaxy Training Network"
            git init
            # Update the origin early
            git remote add origin https://github.com/hexylena/git-gat
            git fetch origin
            # Wipe out the tags that do exist
            git tag -l | xargs git tag -d

            for i in {0..9}; do
                # Commit those patches
                git am $i-*.patch || true;
                # And tag it
                git tag "step-$i";
            done
            git add .scripts/
            git commit -m "admin/final/0000: Add scripts directory"
            rm -f *.patch
            ls -al

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.GIT_GAT_SSH_KEY }}
          known_hosts: "github.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ=="
          if_key_exists: ignore # replace / ignore / fail; optional (defaults to fail)

      - name: Push
        run: |
            cd /tmp/git-gat/
            git remote set-url origin git@github.com:hexylena/git-gat.git
            git push -f -u origin main
            git push --tags
