name: Build GIT-GAT

on: [pull_request]
  #push:
    #branches:
      #- main

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - uses: actions/setup-python@v2
        with:
          python-version: '3.7'
          architecture: 'x64'

      - name: Build git-gat repo
        run: |
            bin/knit-automated.sh export;
            cd /tmp/git-gat/;
            git init;
            git am *.patch;
            rm *.patch;
            ls -al;
