---
# https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#example-using-a-list-of-events
on: [pull_request]

jobs:
  setup:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: [2.7]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Install dependencies
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3

  lint-frontmatter:
    needs: setup
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: [2.7]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - run: make check-frontmatter ACTIVATE_ENV=pwd

  lint-workflows:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - run: make check-workflows

  lint-snippets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - run: make check-snippets

  build-site:
    needs: setup
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: [2.7]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - run: bundle exec jekyll build --strict_front_matter -d _site/training-material
      - uses: actions/upload-artifact@v2
        with:
          name: site-build
          path: _site

  htmlproofer:
    needs: build-site
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: [2.7]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - run: bundle exec jekyll build --strict_front_matter -d _site/training-material
      - uses: actions/download-artifact@v2
        with:
          name: site-build
      - run: ls -R
      - run: make _check-html ACTIVATE_ENV=pwd
