name: Workflow testing

on:
  schedule:
    # 4am every month
    - cron:  '0 4 1 * *'

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        server: [eu, org, org.au]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      # BEGIN Dependencies
      - uses: actions/setup-python@v2
        with:
          python-version: '3.7'
          architecture: 'x64'
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "2.5"
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - uses: actions/cache@v2
        with:
          path: |
            vendor/bundle
            ~/.cache/pip
            ~/.npm
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}-py-${{ hashFiles('**/requirements.txt') }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}-py-${{ hashFiles('**/requirements.txt') }}-node-
            ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}-py--node-
            ${{ runner.os }}-gems-
      - name: Install dependencies
        run: |
          gem install bundler
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
          pip install -r requirements.txt
          npm install
      # END Dependencies

      - name: Configure AWS credentials from GTN account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Obtain tag name
        id: branch_name
        run: |
          echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}

      - name: Build Site
        run: |
          gem install bundler
          sed -i s"|^baseurl: .*|baseurl: '/archive/${SOURCE_TAG}'|g" _config.yml
          sed -i s"|^github_repository_branch: .*|github_repository_branch: '${SOURCE_TAG}'|g" _config.yml
          JEKYLL_ENV=production bundle exec jekyll build --strict_front_matter -d _site/training-material
        env:
          SOURCE_TAG: ${{ steps.branch_name.outputs.SOURCE_TAG }}
          GTN_FORK: ${{ github.repository_owner }}

      - name: Deploy 🚀
        run: |
          pip install awscli
          ./bin/publish-archive
        env:
          SOURCE_TAG: ${{ steps.branch_name.outputs.SOURCE_TAG }}
